# Get rid of the newline at the start
add_newline = false

# The "Prime" format: just the directory and the git status
format = """
$character\
$directory\
$git_branch\
$git_status\
"""

palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'



[directory]
style = "foam"
truncation_length = 2
truncation_symbol = ""

[git_branch]
style = "bold love"
format = "[git:\\(](blue)[$branch]($style)[\\)](blue) "

[git_status]
style = "bold iris"
format = "([$all_status$ahead_behind]($style)) "

[character]
success_symbol = "[ ](bold green)"
error_symbol = "[ ](bold red)"
vimcmd_symbol = "[ ](bold green)"
